export const marketItems = [
    {
        img: "/img/batman.jpg",
        id: "1",
        price: "100",
        name: "Batman show",
        description: "Get a special look at Samsungs 2022 lineup of Neo QLED 8K TVs, soundbars, accessories and sustainability initiatives. With this new lineup, Samsung aims to redefine the role of television by creating beautifully designed, cutting-edge screens that offer more than just entertainment to create one central hub to play, connect, work and more. While you’re at 837X, be sure to jump into the all-new You Make It experience, featuring three quests that celebrate individuality through customization. Be one of the first 20,000 to finish all three quests and you’ll receive a unique piece of NFT art that’s powered by Pixelmind and personalized according to your own You Make It experience.",
        motovition: "Take the lead. Create your own world.",
        organizedBy: "batman",
        starting: "april 15",
        ending: "april 20",
         city: "AETHERIAN project",
         telegram: "/img/telegram.png",
         discord: "/img/discord.png",
        
        
    },
    {
        img: "/img/ticket-1.jpg",
        id: "2",
        price: "120",
        name: "monkey club shades",
        description: "Take a selfie screenshot in front of the TGMC SHADES banner in the TGMC building in decentraland and post your photo in the reply of this tweet. @tgmc_dcl",
        organizedBy: "monkey fns",
        starting: "april 15",
        ending: "april 20",
         city: "AETHERIAN project",
         telegram: "/img/telegram.png",
         discord: "/img/discord.png",
    },
    {
        img: "/img/ticket-2.jpg",
        id: "3",
        price: "300.6",
        name: "City Hall of Love",
        description: "Calling all lovers, Closeup City Hall of Love is live in Decentraland! Youre invited to a world built on the freedom to love, where everyone is free marry whoever they choose.Mint your free NFT Certificate of Marriage. Immortalise your love on the blockchain.",
        organizedBy: "batman",
        starting: "april 15",
        ending: "april 20",
         city: "AETHERIAN project",
         telegram: "/img/telegram.png",
         discord: "/img/discord.png",
    },
    {
        img: "/img/flowers.png",
        id: "4",
        price: "145.6",
        name: "PARCEL LAUNCH PARTY",
        description: "Come celebrate the grand opening of MetaRax! DJ T-Raxs new hangout spot in Decentraland!",
        organizedBy: "batman",
        starting: "april 15",
        ending: "april 20",
         city: "AETHERIAN project",
         telegram: "/img/telegram.png",
         discord: "/img/discord.png",
    },
    {
        img: "/img/samsung.png",
        id: "5",
        price: "50",
        name: "Samsung 837X",
        description: "Get a special look at Samsungs 2022 lineup of Neo QLED 8K TVs, soundbars, accessories and sustainability initiatives. With this new lineup, Samsung aims to redefine the role of television by creating beautifully designed, cutting-edge screens that offer more than just entertainment to create one central hub to play, connect, work and more. While you’re at 837X, be sure to jump into the all-new You Make It experience, featuring three quests that celebrate individuality through customization. Be one of the first 20,000 to finish all three quests and you’ll receive a unique piece of NFT art that’s powered by Pixelmind and personalized according to your own You Make It experience.",
        motovition: "Take the lead. Create your own world.",
        organizedBy: "batman",
        starting: "april 15",
        ending: "april 20",
         city: "AETHERIAN project",
         telegram: "/img/telegram.png",
         discord: "/img/discord.png",
        
    },
    {
        img: "/img/ticket-3.jpg",
        id: "6",
        price: "70",
        name: "monkey club shades",
        description: "Take a selfie screenshot in front of the TGMC SHADES banner in the TGMC building in decentraland and post your photo in the reply of this tweet. @tgmc_dcl",
        organizedBy: "batman",
        starting: "april 15",
        ending: "april 20",
         city: "AETHERIAN project",
         telegram: "/img/telegram.png",
         discord: "/img/discord.png",
    },
    {
        img: "/img/ticket-4.jpg",
        id: "7",
        price: "86",
        name: "City Hall of Love",
        description: "Calling all lovers, Closeup City Hall of Love is live in Decentraland! Youre invited to a world built on the freedom to love, where everyone is free marry whoever they choose.Mint your free NFT Certificate of Marriage. Immortalise your love on the blockchain.",
        organizedBy: "batman",
        starting: "april 15",
        ending: "april 20",
         city: "AETHERIAN project",
         telegram: "/img/telegram.png",
         discord: "/img/discord.png",
    },
    {
        img: "/img/ticket-6.jpg",
        id: "8",
        price: "400",
        name: "PARCEL LAUNCH PARTY",
        description: "Come celebrate the grand opening of MetaRax! DJ T-Raxs new hangout spot in Decentraland!",
        organizedBy: "batman",
        starting: "april 15",
        ending: "april 20",
         city: "AETHERIAN project",
         telegram: "/img/telegram.png",
         discord: "/img/discord.png",
    },
    {
        img: "/img/batman.jpg",
        id: "9",
        price: "100",
        name: "Samsung 837X",
        description: "Get a special look at Samsungs 2022 lineup of Neo QLED 8K TVs, soundbars, accessories and sustainability initiatives. With this new lineup, Samsung aims to redefine the role of television by creating beautifully designed, cutting-edge screens that offer more than just entertainment to create one central hub to play, connect, work and more. While you’re at 837X, be sure to jump into the all-new You Make It experience, featuring three quests that celebrate individuality through customization. Be one of the first 20,000 to finish all three quests and you’ll receive a unique piece of NFT art that’s powered by Pixelmind and personalized according to your own You Make It experience.",
        motovition: "Take the lead. Create your own world.",
        organizedBy: "batman",
        starting: "april 15",
        ending: "april 20",
         city: "AETHERIAN project",
         telegram: "/img/telegram.png",
         discord: "/img/discord.png",
    },
    {
        img: "/img/ticket-1.jpg",
        id: "10",
        price: "120",
        name: "monkey club shades",
        description: "Take a selfie screenshot in front of the TGMC SHADES banner in the TGMC building in decentraland and post your photo in the reply of this tweet. @tgmc_dcl",
        organizedBy: "batman",
        starting: "april 15",
        ending: "april 20",
         city: "AETHERIAN project",
         telegram: "/img/telegram.png",
         discord: "/img/discord.png",
    },
    {
        img: "/img/ticket-2.jpg",
        id: "11",
        price: "300.6",
        name: "City Hall of Love",
        description: "Calling all lovers, Closeup City Hall of Love is live in Decentraland! Youre invited to a world built on the freedom to love, where everyone is free marry whoever they choose.Mint your free NFT Certificate of Marriage. Immortalise your love on the blockchain.",
        organizedBy: "batman",
        starting: "april 15",
        ending: "april 20",
         city: "AETHERIAN project",
         telegram: "/img/telegram.png",
         discord: "/img/discord.png",
    },
    {
        img: "/img/flowers.png",
        id: "12",
        price: "145.6",
        name: "PARCEL LAUNCH PARTY",
        description: "Come celebrate the grand opening of MetaRax! DJ T-Raxs new hangout spot in Decentraland!",
        organizedBy: "batman",
        starting: "april 15",
        ending: "april 20",
         city: "AETHERIAN project",
         telegram: "/img/telegram.png",
         discord: "/img/discord.png",
    },
    {
        img: "/img/samsung.png",
        id: "13",
        price: "50",
        name: "Samsung 837X",
        description: "Get a special look at Samsungs 2022 lineup of Neo QLED 8K TVs, soundbars, accessories and sustainability initiatives. With this new lineup, Samsung aims to redefine the role of television by creating beautifully designed, cutting-edge screens that offer more than just entertainment to create one central hub to play, connect, work and more. While you’re at 837X, be sure to jump into the all-new You Make It experience, featuring three quests that celebrate individuality through customization. Be one of the first 20,000 to finish all three quests and you’ll receive a unique piece of NFT art that’s powered by Pixelmind and personalized according to your own You Make It experience.",
        motovition: "Take the lead. Create your own world.",
        organizedBy: "batman",
        starting: "april 15",
        ending: "april 20",
         city: "AETHERIAN project",
         telegram: "/img/telegram.png",
         discord: "/img/discord.png",
    },
    {
        img: "/img/ticket-3.jpg",
        id: "14",
        price: "70",
        name: "monkey club shades",
        description: "Take a selfie screenshot in front of the TGMC SHADES banner in the TGMC building in decentraland and post your photo in the reply of this tweet. @tgmc_dcl",
        organizedBy: "batman",
        starting: "april 15",
        ending: "april 20",
         city: "AETHERIAN project",
         telegram: "/img/telegram.png",
         discord: "/img/discord.png",
    },
    {
        img: "/img/ticket-4.jpg",
        id: "15",
        price: "86",
        name: "City Hall of Love",
        description: "Calling all lovers, Closeup City Hall of Love is live in Decentraland! Youre invited to a world built on the freedom to love, where everyone is free marry whoever they choose.Mint your free NFT Certificate of Marriage. Immortalise your love on the blockchain.",
        organizedBy: "batman",
        starting: "april 15",
        ending: "april 20",
         city: "AETHERIAN project",
         telegram: "/img/telegram.png",
         discord: "/img/discord.png",

    },
    {
        img: "/img/ticket-6.jpg",
        id: "16",
        price: "400",
        name: "PARCEL LAUNCH PARTY",
        description: "Come celebrate the grand opening of MetaRax! DJ T-Raxs new hangout spot in Decentraland!",
        organizedBy: "batman",
        starting: "april 15",
        ending: "april 20",
         city: "AETHERIAN project",
         telegram: "/img/telegram.png",
         discord: "/img/discord.png",
    },
    {
        img: "/img/batman.jpg",
        id: "17",
        price: "100",
        name: "Samsung 837X",
        description: "Get a special look at Samsungs 2022 lineup of Neo QLED 8K TVs, soundbars, accessories and sustainability initiatives. With this new lineup, Samsung aims to redefine the role of television by creating beautifully designed, cutting-edge screens that offer more than just entertainment to create one central hub to play, connect, work and more. While you’re at 837X, be sure to jump into the all-new You Make It experience, featuring three quests that celebrate individuality through customization. Be one of the first 20,000 to finish all three quests and you’ll receive a unique piece of NFT art that’s powered by Pixelmind and personalized according to your own You Make It experience.",
        motovition: "Take the lead. Create your own world.",
        organizedBy: "batman",
        starting: "april 15",
        ending: "april 20",
         city: "AETHERIAN project",
         telegram: "/img/telegram.png",
         discord: "/img/discord.png",
    },
    {
        img: "/img/ticket-1.jpg",
        id: "18",
        price: "120",
        name: "monkey club shades",
        description: "Take a selfie screenshot in front of the TGMC SHADES banner in the TGMC building in decentraland and post your photo in the reply of this tweet. @tgmc_dcl",
        organizedBy: "batman",
        starting: "april 15",
        ending: "april 20",
         city: "AETHERIAN project",
         telegram: "/img/telegram.png",
         discord: "/img/discord.png",
    },
    {
        img: "/img/ticket-2.jpg",
        id: "19",
        price: "300.6",
        name: "City Hall of Love",
        description: "Calling all lovers, Closeup City Hall of Love is live in Decentraland! Youre invited to a world built on the freedom to love, where everyone is free marry whoever they choose.Mint your free NFT Certificate of Marriage. Immortalise your love on the blockchain.",
        organizedBy: "batman",
        starting: "april 15",
        ending: "april 20",
         city: "AETHERIAN project",
         telegram: "/img/telegram.png",
         discord: "/img/discord.png",

    },
    {
        img: "/img/flowers.png",
        id: "20",
        price: "145.6",
        name: "PARCEL LAUNCH PARTY",
        description: "Come celebrate the grand opening of MetaRax! DJ T-Raxs new hangout spot in Decentraland!",
        organizedBy: "batman",
        starting: "april 15",
        ending: "april 20",
         city: "AETHERIAN project",
         telegram: "/img/telegram.png",
         discord: "/img/discord.png",
    },
    {
        img: "/img/samsung.png",
        id: "21",
        price: "50",
        name: "Samsung 837X",
        description: "Get a special look at Samsungs 2022 lineup of Neo QLED 8K TVs, soundbars, accessories and sustainability initiatives. With this new lineup, Samsung aims to redefine the role of television by creating beautifully designed, cutting-edge screens that offer more than just entertainment to create one central hub to play, connect, work and more. While you’re at 837X, be sure to jump into the all-new You Make It experience, featuring three quests that celebrate individuality through customization. Be one of the first 20,000 to finish all three quests and you’ll receive a unique piece of NFT art that’s powered by Pixelmind and personalized according to your own You Make It experience.",
        motovition: "Take the lead. Create your own world.",
        organizedBy: "batman",
        starting: "april 15",
        ending: "april 20",
         city: "AETHERIAN project",
         telegram: "/img/telegram.png",
         discord: "/img/discord.png",
    },
    {
        img: "/img/ticket-3.jpg",
        id: "22",
        price: "70",
        name: "monkey club shades",
        description: "Take a selfie screenshot in front of the TGMC SHADES banner in the TGMC building in decentraland and post your photo in the reply of this tweet. @tgmc_dcl",
        organizedBy: "batman",
        starting: "april 15",
        ending: "april 20",
         city: "AETHERIAN project",
         telegram: "/img/telegram.png",
         discord: "/img/discord.png",
    },
    {
        img: "/img/ticket-4.jpg",
        id: "23",
        price: "86",
        name: "City Hall of Love",
        description: "Calling all lovers, Closeup City Hall of Love is live in Decentraland! Youre invited to a world built on the freedom to love, where everyone is free marry whoever they choose.Mint your free NFT Certificate of Marriage. Immortalise your love on the blockchain.",
        organizedBy: "batman",
        starting: "april 15",
        ending: "april 20",
         city: "AETHERIAN project",
         telegram: "/img/telegram.png",
         discord: "/img/discord.png",
    },
    {
        img: "/img/ticket-6.jpg",
        id: "24",
        price: "400",
        name: "PARCEL LAUNCH PARTY",
        description: "Come celebrate the grand opening of MetaRax! DJ T-Raxs new hangout spot in Decentraland!",
        organizedBy: "batman",
        starting: "april 15",
        ending: "april 20",
         city: "AETHERIAN project",
         telegram: "/img/telegram.png",
         discord: "/img/discord.png",

    },
    
]